services:
  config-service:
    container_name: config-service
    image: config-service:1.0
    ports:
      - "8888:8888"
    networks:
      ecommerce-network:

  service-discovery:
    container_name: service-discovery
    image: service-discovery:2.0
    ports:
      - "8761:8761"
    networks:
      ecommerce-network:

  kafka:
    image: confluentinc/cp-kafka:8.3.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 설정
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 컨테이너 내부와 Windows 외부 접속을 분리
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_LISTENERS: >
        INTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:29093,
        EXTERNAL://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # 단일 브로커 개발 환경
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # 자동 토픽 생성
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # KRaft 클러스터 ID
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    volumes:
      - kafka-data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - ecommerce-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:8.3.0
    container_name: kafka-connect
    hostname: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8083:8083"

    environment:
      # Connect에서 Kafka 컨테이너로 접속할 때는 localhost가 아니라
      # Kafka 서비스명과 내부 포트를 사용
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"

      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect

      # Connect 클러스터 식별자
      CONNECT_GROUP_ID: kafka-connect-group

      # Connect 내부 관리 토픽
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status

      # 단일 브로커 개발 환경
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # JSON Converter
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"

      # 플러그인 검색 경로
      CONNECT_PLUGIN_PATH: >
        /usr/share/java,
        /usr/share/confluent-hub-components,
        /usr/share/custom-connectors

      # Log4j2 로그 설정
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: >
        org.apache.kafka.connect.runtime.rest=WARN,
        org.reflections=ERROR

    volumes:
      # Windows의 connectors 폴더를 컨테이너에 연결
      - ./kafka-connect/connectors:/usr/share/custom-connectors

    networks:
      - ecommerce-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      ecommerce-network:

  mariadb-server:
    image: mariadb:11.8
    container_name: mariadb-server
    restart: unless-stopped

    ports:
      - "13306:3306"

    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: mydb
      TZ: Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0

    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb-sink/init:/docker-entrypoint-initdb.d

    networks:
      - ecommerce-network

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
#  apigateway-service:

volumes:
  kafka-data:
  mariadb-data:
    name: mariadb-data

networks:
  ecommerce-network:
    external: true