server:
  port: 8082

spring:
  application:
    name: order-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

management:
  tracing:
    sampling:
      probability: 1.0      # 1.0이면 100% 샘플링 (개발/테스트 환경에서 유용)
  propagation:
    consume: w3c
    produce: w3c
    otlp:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans   # Zipkin HTTP endpoint 사용
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh
          - env