server:
  port: 8088

spring:
  application:
    name: springboot-admin

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - env
          - metrics